FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y gnudatalanguage sudo xorg-dev libcfitsio-dev libcanberra-gtk-module

COPY *.pro /
COPY justco* /
COPY dummy* /

CMD ["gdl", "go.pro"]

