file='moonalbedo.dat'
map1=get_data(file)
help,map1
file='basemap.dat'
map2=get_data(file)
help,map2
;-------------------
window,1,title='Clementine/Matlab'
contour,map1,/cell_fill,levels=findgen(25)/25.*256
window,0,title='Basemap'
contour,map2,/cell_fill,levels=findgen(25)/25.*256
end
