PRO get_pixel_ratio,im,ratio,CCDfactor
; these coordinates should be set up after examination of an image 
; generated by eshine_XX using e.g. DS9
w=2	; half-width of the window, in pixels
xDS=129/float(CCDfactor) & yDS=243/float(CCDfactor)	; x,y of the DS region centre pixel
xBS=372/float(CCDfactor) & yBS=297/float(CCDfactor)	; x,y of the BS region centre pixel
a=im(xDS-w:xDS+w,yDS-w:yDS+w)
b=im(xBS-w:xBS+w,yBS-w:yBS+w)
ratio=total(a,/double)/total(b,/double)
return
end
