del2='.FIT'
del1='~/Desktop/ASTRO/MOON/May27/obsrun1/IMG'
del1='~/Desktop/ASTRO/MOON/May26/Obsrun1/IMG'
imstart=1
imstop=430
;imstop=imstart+10
for imnum=imstart,imstop,1 do begin
file=strcompress(del1+string(imnum)+del2,/remove_all)
image=readfits(file,header)
l=size(image,/dimension)
;image=rebin(image,l(0)/2,l(1)/2)
tvscl,image
obsdate=header(10)
obstime=header(11)
;print,header
print,obstime,file
a=''
read,a
endfor
end
