read_jpeg,'CERES_reflectedflux.jpg',flux 
read_jpeg,'CERES_radiance.jpg',radiance
R=float(reform(flux(0,*,*)))/float(reform(radiance(0,*,*)))  
G=float(reform(flux(1,*,*)))/float(reform(radiance(1,*,*)))  
B=float(reform(flux(2,*,*)))/float(reform(radiance(2,*,*)))  
im=flux*0.0
im(0,*,*)=r(*,*)
im(1,*,*)=g(*,*)
im(2,*,*)=b(*,*)
write_jpeg,'fluxoverradiance.jpg',byte(im),quality=100,TRUE=1
end
