scenario=fltarr(360,181)
lon=findgen(360)
lat=findgen(181)-90
file='scenario_dat.lapalma'
data=get_data(file)
x=reform(data(0,*))
y=reform(data(1,*))
openr,1,'titelstring.lapalma'
s=''
readf,1,s
close,1
map_set,/mollweide,title=s
map_continents,/overplot,title=title,/fill,color=2
for i=0,n_elements(x)-1,1 do begin
print,x(i),y(i),y(i)+90
scenario(x(i),y(i)+90)=1
endfor
contour,scenario,lon,lat,/cell_fill,/overplot
map_continents,/overplot,title=title,color=255,mlinethick=2
end
