data=get_data('jupiter_stats.dat')
mn=reform(data(0,*))
var=reform(data(1,*))
mom3=reform(data(2,*))
mom4=reform(data(3,*))
!P.MULTI=[0,1,4]
!P.CHARSIZE=1.2
plot,mn,ytitle='Mean',xstyle=1,ystyle=3
plot,var,ytitle='Variance',xstyle=1,ystyle=3
plot,mom3,ytitle='Skewness',xstyle=1,ystyle=3
plot,mom4,ytitle='Curtosis',xstyle=1,ystyle=3
end
