data=get_data('effectofnpixels.dat')
n=reform(data(0,*))
data=data(1:6,*)
plot_io,yrange=[1e-5,1e-2],abs(data(0,*))
colnam=['red','green','blue','orange','gray']
oplot,abs(data(1,*)),color=fsc_color(colnam(0))
oplot,abs(data(2,*)),color=fsc_color(colnam(1))
oplot,abs(data(3,*)),color=fsc_color(colnam(2))
oplot,abs(data(4,*)),color=fsc_color(colnam(3))
oplot,abs(data(5,*)),color=fsc_color(colnam(4))
end
