data=get_data('moments.dat')
mn=reform(data(0,*))
var=reform(data(1,*))
skew=reform(data(2,*))
curt=reform(data(3,*))
albedo=reform(data(4,*))
!P.charsize=2
!P.MULTI=[0,2,2]
plot,albedo,mn,xstyle=3,ystyle=1,ytitle='Mean',xtitle='SSA',psym=7
plot,albedo,var,xstyle=3,ystyle=1,ytitle='Variance',xtitle='SSA',psym=7
plot,albedo,skew,xstyle=3,ystyle=1,ytitle='Skewness',xtitle='SSA',psym=7
plot,albedo,curt,xstyle=3,ystyle=1,ytitle='Curtosis',xtitle='SSA',psym=7
end
