psf=readfits('SCIENCEPROJECTS/EARTHSHINE/psf.fit')
in=readfits('ideal_folded_out.fits')
rong_out=readfits('multipliedfile.fit')/512.^4
print,max(rong_out),total(rong_out)
pth_out=fft(fft(psf,-1,/double)*fft(in,-1,/double),1,/double)
pth_out=sqrt(double(pth_out*conj(pth_out)))
print,max(pth_out),total(pth_out)
writefits,'pth_out.fits',pth_out
diff=rong_out-pth_out
writefits,'diff.fits',diff
writefits,'diff_pct.fits',diff/pth_out*100.0
end
