PRO equalize_histograms,x,y
fcn=HIST_EQUAL(x,/histogram_only)
y = HIST_EQUAL( y,FCN=FCN)
return
end
;=============================
n=10000
x=randomn(seed,n)
x=bytscl(x)
;---
y=randomn(seed,n)
y=sqrt(y)
y=bytscl(y)
h=histogram(x)
h2=histogram(y)
!P.MULTI=[0,1,2]
print,moment(x)
print,moment(y)
plot,h,thick=2
oplot,h2
;
equalize_histograms,x,y
print,moment(x)
print,moment(y)
h=histogram(x)
h2=histogram(y)
plot,h,thick=2
oplot,h2
end
