psf=dblarr(1536,1536)
openr,1,'PSF.bin'
readu,1,psf
close,1
psf=psf^1.8
volume=total(psf,/double)
print,'Vol:',volume
psf=psf/volume
;
jacobs=fltarr(1536,1536)
openr,1,'psf_1.8_normalized.raw'
readu,1,jacobs
close,1
;
diff=psf-jacobs
pct=diff/jacobs*100.0
!P.CHARSIZE=2
surface,pct,ztitle='% different',title='FSFs'
end
