PRO add_telescope_and_filter_effects,image,filter,phase_angle_E,imsize, $
	filterfact, skylevel, if_sky



;-----------------------------------------------------------------------
; add the sky - the Poisson noise will be generated by the call to generate_CCD
;-----------------------------------------------------------------------

if (if_sky eq 1) then begin
    sky=skylevel
    image=image+sky
endif

;-----------------------------------------------------------------------
; Add a half-filter.
;-----------------------------------------------------------------------
if (filter GE 1 and phase_angle_E LE 180.0) then begin
  for iy=imsize/2,imsize-1 do image[iy,*] = image[iy,*]/float(filterfact)
endif else if (filter GE 1 and phase_angle_E GT 180.0) then begin
  for iy=0,imsize/2-1 do image[iy,*] = image[iy,*]/float(filterfact)
endif

return
end